fs1=frozenset([1,2,3,4,5])
print(type(fs1))
for i in fs1:
    print(i)
print(1 in fs1)
print(10 in fs1)
print("copy() of frozenset:")
fruits1 = frozenset(["apple", "banana", "orange"])
print(fruits1) 
fruits2 = fruits1.copy()
print(fruits2)
print("Union of frozenset:")
frozenset1=fs1.union(fruits1)
print(frozenset1)

print("Intersection of frozenset:")
fs2=([4,5,6,7,8,9])
frozenset2=fs1.intersection(fs2)
print(frozenset2)
print("Difference of frozenset:")
frozenset3=fs1.difference(fs2)
print(frozenset3)
print("Symmetric Difference of frozenset:")
frozenset4=fs1.symmetric_difference(fs2)
print(frozenset4)

print("Conversion of frozenset into set:")
mset= set(fs1)
print(mset)