import numpy as np 
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print("original array: ",arr)
new_arr=arr.reshape(4,3)
print("New array: ")
print(new_arr)
print()
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])

print("Addition of array: ",arr1+arr2)
print("Subtraction of array: ",arr1-arr2)
print("Multiplication of array: ",arr1*arr2)
print("Division of array: ",arr1/arr2)
print("Transpose of array: ",arr1**arr2)